name: fetch_five
description: "Fetch your way to five in a row!"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7
  get: ^4.6.6
  flutter_svg: ^2.0.14
  clay_containers: ^0.3.4
  device_preview: ^1.2.0
  desktop_window: ^0.4.2
  popover: ^0.3.1
  responsive_framework: ^1.5.1
  dio: ^5.7.0
  logger: ^2.5.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3


dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0


flutter_gen:
  output: lib/app/data/gen

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/